### ISSUE TITLE
ImportError: No module named scrapyjs

### ISSUE THREAD

**Issue by joanpavlidou** [louisguitton/disqus-crawler#1]
Could you please help me with that error I am getting when running the script?

ImportError: No module named scrapyjs

I get some other errors too but I hope that are related to that one.

Thank you!

**Comment by louisguitton** [comment]
HI @joanpavlidou ,
Thanks for using my repo and asking this question.
My code was 2 years old and the `scrapyjs` module got renamed to `scrapy_splash`. Therefore the code was broken.

I've made the changes and updated the `Readme.md` accordingly. I've tested it and it works now!
Let me know if you run into other issues.

**Comment by joanpavlidou** [comment]
Thank you very much, Louis, for your timely response, your help and your very good work. Yes, it works!!!
